<?php

namespace App\Filament\Resources\Equipment\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class EquipmentTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')
                    ->label('ID')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('name')
                    ->searchable(),
                TextColumn::make('item_type1')
                    ->searchable(),
                TextColumn::make('item_type2')
                    ->searchable(),
                TextColumn::make('item_grade')
                    ->searchable(),
                TextColumn::make('attack_power')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('attack_power_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('defense')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('defense_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_amp')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_amp_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_amp_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_amp_ratio_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('adaptive_force')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('adaptive_force_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_hp')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_hp_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('mas_sp')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('mas_sp_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hp_regen')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hp_regen_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sp_regen')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sp_regen_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('attack_speed_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('attack_speed_ratio_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('critical_strike_chance')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('critical_strike_damage')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_critical_strike_damaged')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cooldown_reduction')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cooldown_limit')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('life_steal')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('normal_life_steal')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_life_steal')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('move_speed')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('move_speed_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('move_speed_out_of_combat')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sight_range')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('attack_range')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('increase_basic_attack_damage')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('increase_basic_attack_damage_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('increase_basic_attack_damage_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('increase_basic_attack_damage_ratio_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_basic_attack_damaged')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_basic_attack_damaged_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_basic_attack_damaged_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_basic_attack_damaged_ratio_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_skill_damaged')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_skill_damaged_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_skill_damaged_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prevent_skill_damaged_ratio_by_lv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('penetration_defense')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('penetration_defense_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('trap_damage_reduce')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('trap_damage_reduce_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('slow_resist_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hp_healed_increase_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('healer_give_hp_heal_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_attack_range')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_hp_healed_increase_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_cooldown_limit')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_tenacity')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_move_speed')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_penetration_defense')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_penetration_defense_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_life_steal')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('unique_skill_amp_ratio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
