<?php

namespace App\Filament\Resources\Equipment\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class EquipmentInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('id')
                    ->label('ID')
                    ->numeric(),
                TextEntry::make('name')
                    ->placeholder('-'),
                TextEntry::make('item_type1')
                    ->placeholder('-'),
                TextEntry::make('item_type2')
                    ->placeholder('-'),
                TextEntry::make('item_grade')
                    ->placeholder('-'),
                TextEntry::make('attack_power')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('attack_power_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('defense')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('defense_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('skill_amp')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('skill_amp_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('skill_amp_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('skill_amp_ratio_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('adaptive_force')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('adaptive_force_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_hp')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_hp_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('mas_sp')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('mas_sp_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hp_regen')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hp_regen_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sp_regen')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sp_regen_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('attack_speed_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('attack_speed_ratio_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('critical_strike_chance')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('critical_strike_damage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_critical_strike_damaged')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('cooldown_reduction')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('cooldown_limit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('life_steal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('normal_life_steal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('skill_life_steal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('move_speed')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('move_speed_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('move_speed_out_of_combat')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sight_range')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('attack_range')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('increase_basic_attack_damage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('increase_basic_attack_damage_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('increase_basic_attack_damage_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('increase_basic_attack_damage_ratio_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_basic_attack_damaged')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_basic_attack_damaged_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_basic_attack_damaged_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_basic_attack_damaged_ratio_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_skill_damaged')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_skill_damaged_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_skill_damaged_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('prevent_skill_damaged_ratio_by_lv')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('penetration_defense')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('penetration_defense_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('trap_damage_reduce')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('trap_damage_reduce_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('slow_resist_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hp_healed_increase_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('healer_give_hp_heal_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_attack_range')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_hp_healed_increase_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_cooldown_limit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_tenacity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_move_speed')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_penetration_defense')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_penetration_defense_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_life_steal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('unique_skill_amp_ratio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
