<?php

namespace App\Filament\Resources\Equipment\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class EquipmentForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->default(null),
                TextInput::make('item_type1')
                    ->default(null),
                TextInput::make('item_type2')
                    ->default(null),
                TextInput::make('item_grade')
                    ->default(null),
                TextInput::make('attack_power')
                    ->numeric()
                    ->default(null),
                TextInput::make('attack_power_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('defense')
                    ->numeric()
                    ->default(null),
                TextInput::make('defense_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('skill_amp')
                    ->numeric()
                    ->default(null),
                TextInput::make('skill_amp_by_level')
                    ->numeric()
                    ->default(null),
                TextInput::make('skill_amp_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('skill_amp_ratio_by_level')
                    ->numeric()
                    ->default(null),
                TextInput::make('adaptive_force')
                    ->numeric()
                    ->default(null),
                TextInput::make('adaptive_force_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('max_hp')
                    ->numeric()
                    ->default(null),
                TextInput::make('max_hp_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('max_sp')
                    ->numeric()
                    ->default(null),
                TextInput::make('max_sp_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('hp_regen')
                    ->numeric()
                    ->default(null),
                TextInput::make('hp_regen_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('sp_regen')
                    ->numeric()
                    ->default(null),
                TextInput::make('sp_regen_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('attack_speed_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('attack_speed_ratio_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('critical_strike_chance')
                    ->numeric()
                    ->default(null),
                TextInput::make('critical_strike_damage')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_critical_strike_damaged')
                    ->numeric()
                    ->default(null),
                TextInput::make('cooldown_reduction')
                    ->numeric()
                    ->default(null),
                TextInput::make('cooldown_limit')
                    ->numeric()
                    ->default(null),
                TextInput::make('life_steal')
                    ->numeric()
                    ->default(null),
                TextInput::make('normal_life_steal')
                    ->numeric()
                    ->default(null),
                TextInput::make('skill_life_steal')
                    ->numeric()
                    ->default(null),
                TextInput::make('move_speed')
                    ->numeric()
                    ->default(null),
                TextInput::make('move_speed_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('move_speed_out_of_combat')
                    ->numeric()
                    ->default(null),
                TextInput::make('sight_range')
                    ->numeric()
                    ->default(null),
                TextInput::make('attack_range')
                    ->numeric()
                    ->default(null),
                TextInput::make('increase_basic_attack_damage')
                    ->numeric()
                    ->default(null),
                TextInput::make('increase_basic_attack_damage_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('increase_basic_attack_damage_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('increase_basic_attack_damage_ratio_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_basic_attack_damaged')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_basic_attack_damaged_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_basic_attack_damaged_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_basic_attack_damaged_ratio_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_skill_damaged')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_skill_damaged_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_skill_damaged_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('prevent_skill_damaged_ratio_by_lv')
                    ->numeric()
                    ->default(null),
                TextInput::make('penetration_defense')
                    ->numeric()
                    ->default(null),
                TextInput::make('penetration_defense_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('trap_damage_reduce')
                    ->numeric()
                    ->default(null),
                TextInput::make('trap_damage_reduce_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('slow_resist_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('hp_healed_increase_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('healer_give_hp_heal_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_attack_range')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_hp_healed_increase_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_cooldown_limit')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_tenacity')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_move_speed')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_penetration_defense')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_penetration_defense_ratio')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_life_steal')
                    ->numeric()
                    ->default(null),
                TextInput::make('unique_skill_amp_ratio')
                    ->numeric()
                    ->default(null),
            ]);
    }
}
