<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class EquipmentResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'item_type1' => $this->item_type1,
            'item_type2' => $this->item_type2,
            'item_type3' => $this->item_type3,
            'item_grade' => $this->item_grade,
            'attack_power' => $this->attack_power,
            'attack_power_by_lv' => $this->attack_power_by_lv,
            'defense' => $this->defense,
            'defense_by_lv' => $this->defense_by_lv,
            'skill_amp' => $this->skill_amp,
            'skill_amp_by_level' => $this->skill_amp_by_level,
            'skill_amp_ratio' => $this->skill_amp_ratio,
            'skill_amp_ratio_by_level' => $this->skill_amp_ratio_by_level,
            'adaptive_force' => $this->adaptive_force,
            'adaptive_force_by_level' => $this->adaptive_force_by_level,
            'max_hp' => $this->max_hp,
            'max_hp_by_lv' => $this->max_hp_by_lv,
            'max_sp' => $this->max_sp,
            'max_sp_by_lv' => $this->max_sp_by_lv,
            'hp_regen' => $this->hp_regen,
            'hp_regen_ratio' => $this->hp_regen_ratio,
            'sp_regen' => $this->sp_regen,
            'sp_regen_ratio' => $this->sp_regen_ratio,
            'attack_speed_ratio' => $this->attack_speed_ratio,
            'attack_speed_ratio_by_lv' => $this->attack_speed_ratio_by_lv,
            'critical_strike_chance' => $this->critical_strike_chance,
            'critical_strike_damage' => $this->critical_strike_damage,
            'prevent_critical_strike_damaged' => $this->prevent_critical_strike_damaged,
            'cooldown_reduction' => $this->cooldown_reduction,
            'cooldown_limit' => $this->cooldown_limit,
            'life_steal' => $this->life_steal,
            'normal_life_steal' => $this->normal_life_steal,
            'skill_life_steal' => $this->skill_life_steal,
            'move_speed' => $this->move_speed,
            'move_speed_ratio' => $this->move_speed_ratio,
            'move_speed_out_of_combat' => $this->move_speed_out_of_combat,
            'sight_range' => $this->sight_range,
            'attack_range' => $this->attack_range,
            'increase_basic_attack_damage' => $this->increase_basic_attack_damage,
            'increase_basic_attack_damage_by_lv' => $this->increase_basic_attack_damage_by_lv,
            'increase_basic_attack_damage_ratio' => $this->increase_basic_attack_damage_ratio,
            'increase_basic_attack_damage_ratio_by_lv' => $this->increase_basic_attack_damage_ratio_by_lv,
            'prevent_basic_attack_damaged' => $this->prevent_basic_attack_damaged,
            'prevent_basic_attack_damaged_by_lv' => $this->prevent_basic_attack_damaged_by_lv,
            'prevent_basic_attack_damaged_ratio' => $this->prevent_basic_attack_damaged_ratio,
            'prevent_basic_attack_damaged_ratio_by_lv' => $this->prevent_basic_attack_damaged_ratio_by_lv,
            'prevent_skill_damaged' => $this->prevent_skill_damaged,
            'prevent_skill_damaged_by_lv' => $this->prevent_skill_damaged_by_lv,
            'prevent_skill_damaged_ratio' => $this->prevent_skill_damaged_ratio,
            'prevent_skill_damaged_ratio_by_lv' => $this->prevent_skill_damaged_ratio_by_lv,
            'penetration_defense' => $this->penetration_defense,
            'penetration_defense_ratio' => $this->penetration_defense_ratio,
            'trap_damage_reduce' => $this->trap_damage_reduce,
            'trap_damage_reduce_ratio' => $this->trap_damage_reduce_ratio,
            'slow_resist_ratio' => $this->slow_resist_ratio,
            'hp_healed_increase_ratio' => $this->hp_healed_increase_ratio,
            'healer_give_hp_heal_ratio' => $this->healer_give_hp_heal_ratio,
            'unique_attack_range' => $this->unique_attack_range,
            'unique_hp_healed_increase_ratio' => $this->unique_hp_healed_increase_ratio,
            'unique_cooldown_limit' => $this->unique_cooldown_limit,
            'unique_tenacity' => $this->unique_tenacity,
            'unique_move_speed' => $this->unique_move_speed,
            'unique_penetration_defense' => $this->unique_penetration_defense,
            'unique_penetration_defense_ratio' => $this->unique_penetration_defense_ratio,
            'unique_life_steal' => $this->unique_life_steal,
            'unique_skill_amp_ratio' => $this->unique_skill_amp_ratio,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'equipment_skills' => EquipmentSkillResource::collection($this->whenLoaded('equipmentSkills')),
        ];
    }
}
